# Generated by Django 4.1 on 2023-04-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro2app', '0006_rename_village_complaints_location_complaints_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='location',
            field=models.TextField(default='null'),
        ),
    ]
