# Generated by Django 4.1 on 2023-04-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro2app', '0008_alter_complaints_complaint_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='solved',
            field=models.BooleanField(default=False),
        ),
    ]
