# Generated by Django 4.1 on 2023-04-25 18:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pro2app', '0010_complaints_dislikes_complaints_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='liked_users',
            field=models.ManyToManyField(blank=True, related_name='liked_complaints', to=settings.AUTH_USER_MODEL),
        ),
    ]
