# Generated by Django 4.1 on 2023-04-25 18:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pro2app', '0011_complaints_liked_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='disliked_users',
            field=models.ManyToManyField(blank=True, related_name='disliked_complaints', to=settings.AUTH_USER_MODEL),
        ),
    ]
