# Generated by Django 4.1 on 2023-04-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro2app', '0013_userinfo_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='feedback',
            field=models.TextField(default=''),
        ),
    ]
