# Generated by Django 4.1 on 2023-04-27 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro2app', '0014_complaints_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaints',
            name='feedback',
        ),
    ]
